<a href="https://colab.research.google.com/github/Krish-nobita903/AUTO-WCE-BLEED-GEN-CHALLENGE/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [ ]:
###Introduction to tensors

In [ ]:
##Creating tensors
#scalar
#Pytroch tensors are created using torch.tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back at python int
scalar.item()

7

In [ ]:
#Vector

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

In [ ]:
Matrix = torch.tensor([[7,8],[9,10]])

In [ ]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
Tensor = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])
Tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
Tensor[1]

IndexError: ignored

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
###Random tensor

In [ ]:
### Random tensor are important because the way many neural
### networks learn is that they start with tensors full of
### random numbers and then adjust those random numbers to better
### represent the data

### Start with random nnumbers -> look at data  -> update random number -> repeat.....

In [ ]:
#Create a random tensor of size(3,4)

In [ ]:
random_tensor = torch.rand(3,4,5)

In [ ]:
random_tensor

tensor([[[0.4845, 0.7639, 0.5327, 0.3779, 0.1877],
         [0.2383, 0.1945, 0.0872, 0.3804, 0.3376],
         [0.8444, 0.4596, 0.3582, 0.1038, 0.4685],
         [0.1672, 0.2463, 0.7031, 0.8413, 0.9986]],

        [[0.1669, 0.7744, 0.5546, 0.0861, 0.1245],
         [0.0816, 0.1891, 0.5554, 0.5704, 0.4153],
         [0.8599, 0.2384, 0.6455, 0.2816, 0.2287],
         [0.9524, 0.9365, 0.7351, 0.7533, 0.8901]],

        [[0.2976, 0.4371, 0.8136, 0.4868, 0.5747],
         [0.0064, 0.3342, 0.7864, 0.4142, 0.9620],
         [0.5160, 0.6244, 0.4122, 0.1597, 0.8787],
         [0.7110, 0.3698, 0.2533, 0.3236, 0.5658]]])

In [ ]:
### Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
### ZEROES AND ONES
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
###Create a tensor of all ones
ones = torch.ones(size=(4,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
#### Create a range of tensors and tensor - like
###Use torch range
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_hundred_with_seven = torch.arange(start = 1,end = 101,step = 7)
one_to_hundred_with_seven

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [ ]:
### Create tensors like
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
###Tensor data types
### NOTE : Tensor datatypes is the one of the 3 big errors you'll
### run into with PyTorch & deep learning
### 1) Tensors not right datatype
### 2) Tensors not right shape
### 3) Tensors not on right device -----(1 on CPU other GPU then error)



float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, ### What datatype is this
                               device=None,### What device is it CPU or GPU
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])